# Travis-CI config
language: python
python:
  - 2.7
  - 3.5

services:
  - docker

install:
  - docker build -t blog .
  - docker run -d -p 127.0.0.1:80:80 -p 127.0.0.1:443:443 --name blog blog

before_script:
  - pip install -r requirements.txt
  - pip install mock
  - pip install requests
  - pip install feedparser

script:
  - docker ps | grep -q blog
  - python tests.py
